services:
  - type: web
    name: people-management-backend
    env: java
    plan: free
    rootDirectory: apirfds220252-BD-Tocken
    buildCommand: chmod +x mvnw && ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SERVICE_TYPE
        value: java
      - key: DATABASE_URL
        value: postgresql://ds2025_user:xR2u2yRz3n4T304liJmsziblpN1IKpNmd@dpg-d6in3bje5dus73e8apb0-a.virginia-postgres.render.com # <-- CORREGIDO
      - key: DB_USERNAME
        value: ds2025_user
      - key: DB_PASSWORD
        value: xR2u2yMrF3n4T304liJwsz1bOpN1IKpM
      - key: app.jwt.secretKey
        value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - key: app.jwt.timeAuthMs
        value: 2400000
